sequenceDiagram
  autonumber
  actor BN as Bệnh nhân
  participant TD as Tiếp đón
  participant C as Clinical
  participant B as Billing
  participant L as Lab
  participant P as Pharmacy

  BN->>TD: Đăng ký / check-in
  TD->>C: Ghi nhận ARRIVED
  C-->>B: appointment.arrived
  B->>B: Tạo phí khám + payment request
  BN->>B: Thanh toán phí khám
  B-->>C: financial.clearance.granted (EXAM)
  C->>C: READY_FOR_EXAM → IN_EXAM
  C->>L: Tạo chỉ định xét nghiệm
  L-->>B: lab.request.created
  B->>B: Tạo phí xét nghiệm
  BN->>B: Thanh toán hóa đơn xét nghiệm
  B-->>L: financial.clearance.granted (LAB)
  L->>L: IN_PROGRESS → COMPLETED
  L-->>C: lab.result.created
  C->>C: Kết luận và hướng xử lý
  alt Điều trị ngoại trú bằng thuốc
    C->>P: Tạo đơn thuốc
    P-->>B: prescription.created
    BN->>B: Thanh toán tiền thuốc
    B-->>P: financial.clearance.granted (DRUG)
    P->>BN: Cấp thuốc
  else Cần nhập viện
    C-->>BN: Lập chỉ định nhập viện
  end
