"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/Button";
import { controlClassName, Field } from "@/components/ui/Field";
import { isUuid } from "@/lib/validation";
import { notificationApi } from "../api";
import type { NotificationChannel } from "../types";

export function SendNotificationForm() {
  const router = useRouter(); const [patientId, setPatientId] = useState(""); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [channel, setChannel] = useState<NotificationChannel>("IN_APP"); const [address, setAddress] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const id = patientId.trim(); const target = address.trim(); if (!isUuid(id)) { setError("Mã bệnh nhân phải là UUID hợp lệ."); return; } if (channel !== "IN_APP" && !target) { setError("Email hoặc số điện thoại người nhận là bắt buộc cho kênh đã chọn."); return; } setSaving(true); setError(null); try { const notification = await notificationApi.send({ patientId: id, title: title.trim(), content: content.trim(), channel, recipientAddress: channel === "IN_APP" ? null : target }); router.push(`/notifications/${notification.notificationId}?notice=sent`); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "Không thể gửi thông báo."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="mt-6 max-w-3xl space-y-5 rounded-xl border border-border bg-surface p-6">{error ? <p role="alert" className="rounded-lg border border-danger/40 bg-danger/10 p-4 text-sm text-danger">{error}</p> : null}<Field label="Mã bệnh nhân" htmlFor="notification-patient" required><input id="notification-patient" required value={patientId} onChange={(event) => setPatientId(event.target.value)} className={controlClassName} /></Field><Field label="Tiêu đề" htmlFor="notification-title" required><input id="notification-title" required maxLength={255} value={title} onChange={(event) => setTitle(event.target.value)} className={controlClassName} /></Field><Field label="Nội dung" htmlFor="notification-content" required><textarea id="notification-content" required rows={6} value={content} onChange={(event) => setContent(event.target.value)} className={controlClassName} /></Field><div className="grid gap-4 md:grid-cols-2"><Field label="Kênh" htmlFor="notification-channel" required><select id="notification-channel" value={channel} onChange={(event) => setChannel(event.target.value as NotificationChannel)} className={controlClassName}><option value="IN_APP">Trong ứng dụng</option><option value="EMAIL">Email</option><option value="SMS">SMS</option></select></Field><Field label="Địa chỉ người nhận" htmlFor="notification-address" required={channel !== "IN_APP"} hint={channel === "IN_APP" ? "Không cần cho thông báo trong ứng dụng." : undefined}><input id="notification-address" disabled={channel === "IN_APP"} required={channel !== "IN_APP"} maxLength={150} value={address} onChange={(event) => setAddress(event.target.value)} className={controlClassName} /></Field></div><div className="flex gap-2"><Button type="submit" variant="primary" loading={saving}>Gửi thông báo</Button><Button type="button" disabled={saving} onClick={() => router.back()}>Quay lại</Button></div></form>;
}
