"use client";

import { useState, type FormEvent } from "react";
import { AsyncState } from "@/components/ui/AsyncState";
import { Button } from "@/components/ui/Button";
import { controlClassName, Field } from "@/components/ui/Field";
import { formatDecimal, formatLocalDate } from "@/lib/format";
import { isUuid } from "@/lib/validation";
import { reportApi } from "../api";
import type { MonthlyReportDTO } from "../types";

export function MonthlyReportView() {
  const now = new Date(); const [month, setMonth] = useState(now.getMonth() + 1); const [year, setYear] = useState(now.getFullYear()); const [departmentId, setDepartmentId] = useState(""); const [report, setReport] = useState<MonthlyReportDTO | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const department = departmentId.trim(); if (department && !isUuid(department)) { setError("Mã khoa phải là UUID hợp lệ."); return; } setLoading(true); setError(null); try { setReport(await reportApi.monthly(month, year, department || undefined)); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "Không thể tải báo cáo tháng."); } finally { setLoading(false); } }
  return <section className="mt-8 rounded-xl border border-border bg-surface p-5"><h2 className="text-lg font-semibold">Doanh thu tháng</h2><form onSubmit={submit} className="mt-4 grid gap-4 md:grid-cols-4 md:items-end"><Field label="Tháng" htmlFor="report-month"><input id="report-month" type="number" min={1} max={12} value={month} onChange={(event) => setMonth(Number(event.target.value))} className={controlClassName} /></Field><Field label="Năm" htmlFor="report-year"><input id="report-year" type="number" min={2000} max={2100} value={year} onChange={(event) => setYear(Number(event.target.value))} className={controlClassName} /></Field><Field label="Mã khoa (tùy chọn)" htmlFor="monthly-department"><input id="monthly-department" value={departmentId} onChange={(event) => setDepartmentId(event.target.value)} className={controlClassName} /></Field><Button type="submit" variant="primary" loading={loading}>Xem theo tháng</Button></form>{error ? <p role="alert" className="mt-3 text-sm text-danger">{error}</p> : null}{loading ? <AsyncState kind="loading" message="Đang tải báo cáo tháng…" /> : null}{report && !loading ? <div className="mt-5"><dl className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-surface-muted p-4"><dt className="text-sm text-muted-foreground">Tổng doanh thu</dt><dd className="mt-1 text-2xl font-semibold">{formatDecimal(report.totalRevenue)}</dd></div><div className="rounded-lg bg-surface-muted p-4"><dt className="text-sm text-muted-foreground">Số hóa đơn</dt><dd className="mt-1 text-2xl font-semibold">{report.invoiceCount}</dd></div></dl><div className="mt-4 overflow-x-auto"><table className="w-full min-w-3xl text-left text-sm"><thead className="border-b border-border"><tr><th className="px-3 py-2">Ngày</th><th className="px-3 py-2">Lượt khám</th><th className="px-3 py-2">Xét nghiệm</th><th className="px-3 py-2">Đơn thuốc</th><th className="px-3 py-2">Doanh thu</th></tr></thead><tbody>{report.dailyDetails.map((day) => <tr key={day.reportDate} className="border-b border-border"><td className="px-3 py-2">{formatLocalDate(day.reportDate)}</td><td className="px-3 py-2">{day.visitCount}</td><td className="px-3 py-2">{day.labCount}</td><td className="px-3 py-2">{day.prescriptionCount}</td><td className="px-3 py-2">{formatDecimal(day.revenue)}</td></tr>)}</tbody></table></div></div> : null}</section>;
}
