"use client";

import { useState, type FormEvent } from "react";
import { AsyncState } from "@/components/ui/AsyncState";
import { Button } from "@/components/ui/Button";
import { controlClassName, Field } from "@/components/ui/Field";
import { isUuid } from "@/lib/validation";
import { reportApi } from "../api";
import type { TopMedicineDTO } from "../types";

export function TopMedicinesView() {
  const today = new Date().toISOString().slice(0, 10); const [fromDate, setFromDate] = useState(today); const [toDate, setToDate] = useState(today); const [departmentId, setDepartmentId] = useState(""); const [limit, setLimit] = useState(10); const [items, setItems] = useState<TopMedicineDTO[] | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const department = departmentId.trim(); if (fromDate > toDate) { setError("Ngày bắt đầu không được sau ngày kết thúc."); return; } if (department && !isUuid(department)) { setError("Mã khoa phải là UUID hợp lệ."); return; } setLoading(true); setError(null); try { setItems(await reportApi.topMedicines(fromDate, toDate, limit, department || undefined)); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "Không thể tải báo cáo thuốc."); } finally { setLoading(false); } }
  return <section className="mt-8 rounded-xl border border-border bg-surface p-5"><h2 className="text-lg font-semibold">Thuốc xuất nhiều nhất</h2><form onSubmit={submit} className="mt-4 grid gap-4 md:grid-cols-5 md:items-end"><Field label="Từ ngày" htmlFor="medicine-from"><input id="medicine-from" type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} className={controlClassName} /></Field><Field label="Đến ngày" htmlFor="medicine-to"><input id="medicine-to" type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} className={controlClassName} /></Field><Field label="Mã khoa" htmlFor="medicine-department"><input id="medicine-department" value={departmentId} onChange={(event) => setDepartmentId(event.target.value)} className={controlClassName} /></Field><Field label="Số kết quả" htmlFor="medicine-limit"><input id="medicine-limit" type="number" min={1} max={50} value={limit} onChange={(event) => setLimit(Number(event.target.value))} className={controlClassName} /></Field><Button type="submit" variant="primary" loading={loading}>Xem xếp hạng</Button></form>{error ? <p role="alert" className="mt-3 text-sm text-danger">{error}</p> : null}{loading ? <AsyncState kind="loading" message="Đang tải xếp hạng thuốc…" /> : null}{items && !loading ? items.length === 0 ? <AsyncState kind="empty" message="Không có dữ liệu xuất thuốc trong khoảng đã chọn." /> : <ol className="mt-5 divide-y divide-border rounded-lg border border-border">{items.map((item, index) => <li key={item.drugId} className="flex items-center gap-4 px-4 py-3"><span className="grid size-8 place-items-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{index + 1}</span><div className="min-w-0 flex-1"><p className="font-medium">{item.drugName}</p><p className="break-all font-mono text-xs text-muted-foreground">{item.drugId}</p></div><strong>{item.totalQuantity}</strong></li>)}</ol> : null}</section>;
}
