ALTER TABLE PROCESSED_EVENT ADD COLUMN payload_hash CHAR(64);
ALTER TABLE NOTIFICATION ADD COLUMN template_key VARCHAR(64);
ALTER TABLE NOTIFICATION ADD COLUMN source_event_id UUID;
ALTER TABLE NOTIFICATION ADD COLUMN source_event_type VARCHAR(100);
ALTER TABLE NOTIFICATION ADD COLUMN source_id UUID;
ALTER TABLE NOTIFICATION ADD COLUMN correlation_id VARCHAR(120);
ALTER TABLE NOTIFICATION ADD COLUMN sensitivity VARCHAR(32) NOT NULL DEFAULT 'STANDARD';
CREATE UNIQUE INDEX uq_notification_source_template_channel
    ON NOTIFICATION(source_event_id,template_key,channel) WHERE source_event_id IS NOT NULL;

CREATE TABLE NOTIFICATION_EVENT_OUTBOX (
    event_id UUID PRIMARY KEY,
    notification_id UUID NOT NULL REFERENCES NOTIFICATION(notification_id),
    payload TEXT NOT NULL,
    publication_enabled BOOLEAN NOT NULL DEFAULT FALSE CHECK (publication_enabled = FALSE),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ
);
