flowchart LR
    subgraph ORG["organization"]
        DEPT["DEPARTMENT"]
        STAFF["STAFF"]
        ACCOUNT["ACCOUNT"]
    end
    subgraph PAT["patient"]
        PATIENT["PATIENT"]
    end
    subgraph CLI["clinical"]
        APPT["APPOINTMENT"]
        MRECORD["MEDICAL_RECORD"]
        DIAG["DIAGNOSIS"]
        ATTACH["RECORD_ATTACHMENT"]
    end
    subgraph LAB["lab"]
        LTEST["LAB_TEST"]
        LRESULT["LAB_RESULT"]
    end
    subgraph PHA["pharmacy"]
        DRUG["DRUG"]
        RX["PRESCRIPTION"]
        RXLINE["PRESCRIPTION_LINE"]
        DSLIP["DISPENSE_SLIP"]
    end
    subgraph BIL["billing"]
        FEE["FEE"]
        INV["INVOICE"]
    end
    subgraph NOT["notification"]
        NOTIF["NOTIFICATION"]
    end
    subgraph REP["report"]
        DVR["DAILY_VISIT_REPORT"]
        MRR["MONTHLY_REVENUE_REPORT"]
        DST["DRUG_STATISTIC"]
    end

    %% ===== Real FK — same service (JOINable) =====
    STAFF -->|department_id FK| DEPT
    DEPT -->|head_of_dept FK| STAFF
    ACCOUNT -->|staff_id FK| STAFF
    MRECORD -->|appointment_id FK| APPT
    DIAG -->|record_id FK| MRECORD
    ATTACH -->|record_id FK| MRECORD
    LRESULT -->|test_id FK| LTEST
    RXLINE -->|prescription_id FK| RX
    RXLINE -->|drug_id FK| DRUG
    DSLIP -->|prescription_id FK 1-1| RX
    FEE -->|invoice_id FK| INV

    %% ===== Bare UUID — cross-service (no JOIN) =====
    APPT -.->|patient_id| PATIENT
    APPT -.->|doctor_id| STAFF
    APPT -.->|department_id| DEPT
    MRECORD -.->|patient_id| PATIENT
    MRECORD -.->|doctor_id| STAFF
    MRECORD -.->|department_id| DEPT
    LTEST -.->|record_id| MRECORD
    LTEST -.->|patient_id| PATIENT
    LTEST -.->|requesting_department_id| DEPT
    RX -.->|record_id| MRECORD
    RX -.->|patient_id| PATIENT
    RX -.->|doctor_id| STAFF
    RX -.->|department_id| DEPT
    DSLIP -.->|dispensed_by| STAFF
    FEE -.->|patient_id| PATIENT
    FEE -.->|record_id| MRECORD
    FEE -.->|department_id| DEPT
    FEE -.->|source_ref_id lab| LTEST
    FEE -.->|source_ref_id rx| RX
    INV -.->|patient_id| PATIENT
    INV -.->|prescription_id| RX
    INV -.->|dispense_id| DSLIP
    NOTIF -.->|patient_id| PATIENT
    DVR -.->|department_id nullable| DEPT
    MRR -.->|department_id nullable| DEPT
    DST -.->|drug_id| DRUG

    %% ===== Events — via mediflow.events (async) =====
    PATIENT ==>|patient.created| NOTIF
    APPT ==>|appointment.created| NOTIF
    APPT ==>|appointment.status.changed| FEE
    MRECORD ==>|medicalrecord.created| LTEST & FEE & DVR & NOTIF
    LTEST ==>|lab.result.created| ATTACH & FEE & NOTIF & DVR
    RX ==>|prescription.created| INV
    DSLIP ==>|prescription.filled| ATTACH & INV & DVR & DST & NOTIF
    DSLIP ==>|prescription.dispense.failed| INV & NOTIF
    INV ==>|payment.completed| DSLIP & LTEST & NOTIF & DVR & MRR
    INV ==>|payment.failed| NOTIF & DVR & MRR
    DRUG ==>|stock.low| NOTIF
    STAFF ==>|staff.department.changed| DVR
